packages:
  - 'apps/*'
  - 'packages/*'
  - 'database'

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@vercel/backends@7.0.0'
  - '@vercel/build-utils@14.9.0'
  - '@vercel/cervel@0.1.59'
  - '@vercel/container@7.0.0'
  - '@vercel/elysia@7.0.0'
  - '@vercel/express@7.0.0'
  - '@vercel/fastify@7.0.0'
  - '@vercel/gatsby-plugin-vercel-builder@2.2.52'
  - '@vercel/go@10.0.0'
  - '@vercel/h3@7.0.0'
  - '@vercel/hono@7.0.0'
  - '@vercel/hydrogen@8.0.0'
  - '@vercel/koa@7.0.0'
  - '@vercel/nestjs@7.0.0'
  - '@vercel/next@11.0.0'
  - '@vercel/node@12.0.0'
  - '@vercel/python@13.0.0'
  - '@vercel/redwood@9.0.0'
  - '@vercel/remix-builder@12.0.0'
  - '@vercel/ruby@9.0.0'
  - '@vercel/rust@8.0.0'
  - '@vercel/static-build@9.0.0'
  - '@vercel/vc-native-darwin-arm64@59.11.1'
  - '@vercel/vc-native-darwin-x64@59.11.1'
  - '@vercel/vc-native-linux-arm64@59.11.1'
  - '@vercel/vc-native-linux-x64@59.11.1'
  - vercel@59.11.1
