import type { Role } from '@/lib/authorization/roles';

/** English catalogue; components consume keys so locale catalogues can replace it centrally. */
export const copy = {
  productName: 'School Management System',
  dashboard: 'Dashboard',
  academic: 'Academic Structure',
  students: 'Students',
  children: 'Children',
  myChildren: 'My Children',
  teachers: 'Teachers',
  parents: 'Parents',
  grades: 'Grades & Results',
  attendance: 'Attendance',
  homework: 'Homework',
  announcements: 'Announcements',
  notifications: 'Notifications',
  navigation: 'Main navigation',
  openNavigation: 'Open navigation',
  closeNavigation: 'Close navigation',
  collapseNavigation: 'Collapse navigation',
  expandNavigation: 'Expand navigation',
  chooseSchool: 'Choose a school',
  chooseSchoolDescription: 'Select one of your active school memberships to continue.',
  switchSchool: 'Switch current school',
  switchingSchool: 'Switching school…',
  noSchool: 'No active school',
  noSchoolDescription: 'Your account does not currently have an active school membership.',
  signInRequired: 'Sign in required',
  signInRequiredDescription: 'An authenticated account is required to open the application.',
  accessDenied: 'Access unavailable',
  accessDeniedDescription: 'This section is not available for your current school role.',
  loadingApplication: 'Loading your workspace…',
  tryAgain: 'Try again',
  requestFailed: 'We could not load this page.',
  requestFailedDescription: 'Please try again. If the problem continues, contact your administrator.',
  dashboardHeading: 'Your school workspace',
  dashboardDescription: 'The shared application foundation is ready. Feature screens will be added in upcoming tasks.',
  currentSchool: 'Current school',
  currentRole: 'Current role',
  foundationReady: 'Application foundation',
  foundationReadyDescription: 'Navigation, tenant context, query caching, and shared interface states are active.',
  comingSoon: 'UI implementation is coming in a later task.',
  backToDashboard: 'Back to dashboard',
} as const;

export const roleLabels: Record<Role, string> = {
  SUPER_ADMIN: 'Super administrator',
  SCHOOL_ADMIN: 'School administrator',
  TEACHER: 'Teacher',
  PARENT: 'Parent',
};
