import { screen, waitFor } from '@testing-library/react'; import userEvent from '@testing-library/user-event'; import { afterEach, describe, expect, it, vi } from 'vitest'; import { ParentsWorkspace } from '@/components/parents/parents-workspace'; import { page, parent, renderParents } from './test-helpers';
const navigation = vi.hoisted(() => ({ search: '', replace: vi.fn() })); vi.mock('next/navigation', () => ({ useSearchParams: () => new URLSearchParams(navigation.search), usePathname: () => '/parents', useRouter: () => ({ replace: navigation.replace }) })); afterEach(() => { vi.restoreAllMocks(); navigation.search = ''; navigation.replace.mockReset(); });
describe('Parent admin permissions and list', () => {
  it('shows SchoolAdmin management without relationship N+1 queries', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json(page([parent]))); renderParents(<ParentsWorkspace />); expect(await screen.findByText('Alaoui')).toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Create Parent' })).toBeInTheDocument(); expect(fetchMock).toHaveBeenCalledTimes(1); expect(String(fetchMock.mock.calls[0]?.[0])).toBe('/api/v1/parents?page=1&pageSize=20'); });
  it('allows current-School SuperAdmin management', async () => { vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json(page([parent]))); renderParents(<ParentsWorkspace />, 'SUPER_ADMIN'); expect(await screen.findByRole('button', { name: 'Create Parent' })).toBeInTheDocument(); });
  it.each(['TEACHER', 'PARENT'] as const)('denies %s before a School-wide Parent request', (role) => { const fetchMock = vi.spyOn(globalThis, 'fetch'); renderParents(<ParentsWorkspace />, role); expect(screen.getByRole('heading', { name: 'Access unavailable' })).toBeInTheDocument(); expect(fetchMock).not.toHaveBeenCalled(); });
  it('uses server filters and pagination metadata', async () => { navigation.search = 'page=2&status=ACTIVE&search=Samira'; const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json(page([parent], 2, 20, 45))); renderParents(<ParentsWorkspace />); expect(await screen.findByText('Page 2 / 3 · 45')).toBeInTheDocument(); expect(String(fetchMock.mock.calls[0]?.[0])).toContain('search=Samira'); await userEvent.click(screen.getByRole('button', { name: 'Next' })); await waitFor(() => expect(navigation.replace).toHaveBeenCalledWith('/parents?page=3&status=ACTIVE&search=Samira', { scroll: false })); });
  it('renders an empty list as a normal state', async () => { vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json(page([]))); renderParents(<ParentsWorkspace />); expect(await screen.findByText('No records yet')).toBeInTheDocument(); });
});
