export const attendanceCopy = {
  title: 'Attendance',
  description: 'Record daily Class Attendance and review authorized Student history.',
  daily: 'Daily roster',
  history: 'Student history',
  dailyDescription: 'Choose an Academic Year, exact Class, and calendar date. The server roster determines historical eligibility.',
  historyDescription: 'Review persisted Attendance records using server-side scope, filters, and pagination.',
  academicYear: 'Academic Year',
  selectYear: 'Select Academic Year',
  klass: 'Class',
  selectClass: 'Select Class',
  date: 'Attendance date',
  student: 'Student',
  status: 'Status',
  note: 'Note',
  notMarked: 'Not marked',
  statuses: { PRESENT: 'Present', ABSENT: 'Absent', LATE: 'Late', EXCUSED: 'Excused' },
  statusFor: (name: string) => `Attendance status for ${name}`,
  noteFor: (name: string) => `Attendance note for ${name}`,
  markAllPresent: 'Mark unmarked present',
  markAllPresentHint: 'This changes form state only and never overwrites an existing Attendance row.',
  save: 'Save Attendance',
  saved: 'Attendance saved atomically.',
  unsaved: 'Unsaved Attendance changes',
  unsavedPrompt: 'Discard unsaved Attendance changes?',
  selectContext: 'Select an Academic Year, Class, and date to load the authoritative roster.',
  futureDate: 'Choose today or an earlier local calendar date. Server UTC-day validation remains authoritative.',
  outsideYear: 'The date must fall within the selected Academic Year.',
  rosterUnavailable: 'Attendance roster unavailable',
  loading: 'Loading Attendance…',
  emptyRoster: 'No historically eligible Students were returned for this Class and date.',
  historicalRoster: 'Eligibility is already resolved from StudentEnrollment effective dates. Current placement is not used to filter these rows.',
  closedClass: 'This Class is not ACTIVE. Existing rows can be corrected, but unmarked rows cannot be created.',
  rosterLimit: 'Each roster page contains at most 100 unique Students, matching the atomic batch limit.',
  searchStudents: 'Search Students by name or code',
  search: 'Search',
  clear: 'Clear',
  selectStudent: 'Select Student',
  allStatuses: 'All statuses',
  dateFrom: 'Date from',
  dateTo: 'Date to',
  invalidDateRange: 'Date from must be on or before date to.',
  historyUnavailable: 'Student Attendance history unavailable',
  noHistory: 'No persisted Attendance records match these filters.',
  noGlobalYear: 'No global current Academic Year is assumed. A sole ACTIVE Year may be preselected only as a local convenience.',
  teacherScope: 'Teacher options are narrowed from ACTIVE assignments; the server enforces exact Class and Academic Year scope.',
  utcLimitation: 'Future-date validation is authoritative against the server UTC calendar day because School timezone is not modeled.',
} as const;
