export const studentCopy = {
  title: 'Students', description: 'Manage Student identity and year-specific enrollment history.',
  readOnly: 'Read-only access', readOnlyDescription: 'Your current role can inspect assigned Students but cannot manage Student or Enrollment records.',
  createStudent: 'Create Student', editStudent: 'Edit Student', studentCreated: 'Student created. Add an Enrollment separately when placement is ready.',
  firstName: 'First name', lastName: 'Last name', studentCode: 'Student code', optional: 'Optional', status: 'Status', actions: 'Actions',
  searchLabel: 'Search Students by name or code', search: 'Search', clear: 'Clear', filterStatus: 'Filter by status', allStatuses: 'All statuses',
  profile: 'Profile', enrollmentHistory: 'Enrollment history', academicPlacement: 'Academic placement',
  openStudent: (name: string) => `Open ${name}`, backToStudents: 'Back to Students', edit: 'Edit',
  noStudents: 'No Students found', noStudentsDescription: 'Create the first Student identity when your School is ready.',
  loadingStudents: 'Loading Students…', loadingStudent: 'Loading Student…', listError: 'Students could not be loaded.',
  unavailable: 'Student unavailable', unavailableDescription: 'This Student is unavailable or outside your current access.',
  academicYear: 'Academic Year', selectYear: 'Select an Academic Year', explicitYear: 'Placement is always resolved for the explicitly selected Academic Year.',
  multipleActiveYears: 'Multiple ACTIVE Academic Years exist. Select the exact Year you want to inspect.',
  placementFor: (name: string) => `Placement for ${name}`, noPlacement: 'No active placement for this Academic Year',
  noPlacementDescription: 'No ACTIVE Enrollment was returned for the selected Year.',
  className: 'Class', effectiveFrom: 'Effective from', effectiveUntil: 'Effective until', ongoing: 'Ongoing',
  addEnrollment: 'Add Enrollment', createEnrollment: 'Create Enrollment', transfer: 'Transfer Student', endEnrollment: 'End Enrollment',
  selectClass: 'Select a Class', noClasses: 'No eligible ACTIVE Classes are available for this Academic Year.',
  enrollmentSeparate: 'Student identity and academic placement are separate. This operation creates only an Enrollment.',
  transferDescription: 'The existing Enrollment will be ended and a new ACTIVE Enrollment will be created. History will remain available.',
  transferDate: 'Transfer effective date', targetClass: 'Target Class',
  transferDateAfter: 'Transfer date must be after the current Enrollment start date.',
  endDescription: 'The Enrollment will be ended on the selected inclusive date. Its historical row will remain available.',
  confirmEnd: 'Confirm end Enrollment', save: 'Save changes', create: 'Create', cancel: 'Cancel', confirm: 'Confirm',
  endDateBefore: 'End date must be on or after the Enrollment start date.',
  changesSaved: 'Changes saved successfully.', placementUpdated: 'Enrollment placement updated successfully.',
  historyEmpty: 'No Enrollment history', historyEmptyDescription: 'Enrollment records will appear here without replacing prior history.',
  page: 'Page', previous: 'Previous', next: 'Next', pagination: 'Student pagination', tryAgain: 'Try again',
  lifecycleTitle: (action: string, name: string) => `${action} ${name}?`,
  lifecycleDescription: (status: string, name: string) => `${name} will move to ${status}. Enrollment and academic history will not be deleted or automatically rewritten.`,
  withdraw: 'Withdraw', archive: 'Archive', activate: 'Activate', deactivate: 'Deactivate',
  noLogin: 'Students do not have V1 login accounts.', unknown: '—',
} as const;
