export const academicCopy = {
  title: 'Academic Structure',
  description: 'Configure school years, levels, curricula, subjects, and classes.',
  readOnly: 'Read-only access',
  readOnlyDescription: 'Your current role can inspect academic structure but cannot change it.',
  sections: {
    years: 'Academic Years', structure: 'Stages & Levels', tracks: 'Tracks',
    subjects: 'Subjects', curricula: 'Curricula', classes: 'Classes',
  },
  add: 'Add', edit: 'Edit', cancel: 'Cancel', save: 'Save changes', create: 'Create',
  retry: 'Try again', actions: 'Actions', status: 'Status', name: 'Name', code: 'Code',
  optional: 'Optional', sequence: 'Order', stage: 'Stage', level: 'Level', track: 'Track',
  noTrack: 'No track', academicYear: 'Academic year', curriculumVersion: 'Curriculum version',
  startDate: 'Start date', endDate: 'End date', coefficient: 'Coefficient', subject: 'Subject',
  displayOrder: 'Display order', page: 'Page', previous: 'Previous', next: 'Next',
  pagination: 'Pagination', academicSections: 'Academic structure sections',
  loadingWorkspace: 'Loading academic structure…', allYears: 'All academic years', allStages: 'All stages', levels: 'Levels',
  loading: 'Loading records…', noRecords: 'No records yet', noRecordsDescription: 'Create the first record when your school is ready.',
  listError: 'Academic structure could not be loaded.',
  mutationSuccess: 'Changes saved successfully.',
  createYear: 'Create academic year', editYear: 'Edit academic year', managePeriods: 'Manage periods',
  periodsFor: (name: string) => `Periods — ${name}`,
  createPeriod: 'Create academic period', editPeriod: 'Edit academic period',
  dateReadOnly: 'Dates are read-only after this record leaves PLANNED status.',
  plannedDependency: 'The server may also protect PLANNED dates once dependent academic records exist.',
  periodBoundary: (start: string, end: string) => `Period dates must stay between ${start} and ${end}.`,
  yearsDescription: 'Academic years are independent; the system does not invent a single global current year.',
  structureDescription: 'Stages organize Levels; each Level keeps its authoritative Stage relationship.',
  levelsDescription: 'Filter and manage Levels through their existing Stage relationship.',
  tracksDescription: 'Tracks are optional School-level pathways and do not belong to a Stage or Level.',
  curriculaDescription: 'Curricula contain named historical versions; versions contain contextual subject coefficients.',
  createStage: 'Create stage', editStage: 'Edit stage', createLevel: 'Create level', editLevel: 'Edit level',
  createTrack: 'Create track', editTrack: 'Edit track', createSubject: 'Create subject', editSubject: 'Edit subject',
  createCurriculum: 'Create curriculum', editCurriculum: 'Edit curriculum',
  versions: 'Curriculum versions', createVersion: 'Create curriculum version', editVersion: 'Edit curriculum version',
  curriculumSubjects: 'Version subjects', attachSubject: 'Attach subject', editCurriculumSubject: 'Edit curriculum subject',
  noCoefficientOnSubject: 'Subject identity has no coefficient. Coefficients are configured inside curriculum versions.',
  draftOnly: 'Structural changes are available only while the curriculum version is DRAFT.',
  duplicateSubject: 'That subject is already attached to this curriculum version.',
  createClass: 'Create class', editClass: 'Edit class', yearImmutable: 'Academic year is historical identity and cannot be changed after creation.',
  searchSubjects: 'Search subjects by name or code', search: 'Search', clear: 'Clear', filterStatus: 'Filter by status', allStatuses: 'All statuses',
  selectCurriculum: 'Select a curriculum to manage its versions.',
  selectVersion: 'Select a curriculum version to inspect its subjects.',
  selectorLoading: 'Loading options…', selectorUnavailable: 'Required options could not be loaded.',
  confirm: 'Confirm lifecycle change', confirmAction: 'Confirm',
  transitionTitle: (action: string, resource: string) => `${action} ${resource}?`,
  transitionDescription: (status: string, resource: string) => `${resource} will move to ${status} according to the committed lifecycle. Existing history will remain available.`,
} as const;
