import { screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AnnouncementDetailWorkspace } from '@/components/announcements/announcement-detail';
import { AnnouncementTargets } from '@/components/announcements/announcement-targets';
import { announcementId, classId, detail, page, publicationId, renderAnnouncements, schoolClass, targetId, version, versionId, year, yearId } from './test-helpers';

vi.mock('next/navigation', () => ({ useRouter: () => ({ push: vi.fn() }) }));
afterEach(() => vi.restoreAllMocks());
function setup() { return vi.spyOn(globalThis, 'fetch').mockImplementation(async (input, init) => { const url = String(input); const method = (init as RequestInit | undefined)?.method;
  if (url === `/api/v1/announcements/${announcementId}` && !method) return Response.json({ data: detail });
  if (url === `/api/v1/announcements/${announcementId}/versions?page=1&pageSize=50` && !method) return Response.json(page([version], 1, 50));
  if ((url === `/api/v1/announcements/${announcementId}/publications?page=1&pageSize=20` || url === `/api/v1/announcements/${announcementId}/publications?page=1&pageSize=100`) && !method) return Response.json(page([], 1, url.endsWith('100') ? 100 : 20));
  if (url === `/api/v1/announcements/${announcementId}/targets?announcementVersionId=${versionId}` && !method) return Response.json({ data: [] });
  if (url === '/api/v1/academic-years?page=1&pageSize=100') return Response.json(page([year], 1, 100));
  if (url === '/api/v1/classes?page=1&pageSize=100') return Response.json(page([schoolClass], 1, 100));
  if (url === `/api/v1/announcements/${announcementId}/versions` && method === 'POST') return Response.json({ data: { ...version, id: crypto.randomUUID(), versionNumber: 2 } }, { status: 201 });
  if (url === `/api/v1/announcements/${announcementId}/targets` && method === 'POST') return Response.json({ data: [{ id: targetId, announcementVersionId: versionId, audience: 'PARENTS', targetType: 'CLASS', academicYearId: yearId, classId }] }, { status: 201 });
  if (url === `/api/v1/announcements/${announcementId}/publish` && method === 'POST') return Response.json({ data: { publicationId, announcementId, announcementVersionId: versionId, publicationVersion: 1, status: 'PUBLISHED', scheduledAt: null, publishedAt: '2026-01-01T00:00:00.000Z', publishedBy: crypto.randomUUID(), idempotencyKey: crypto.randomUUID(), eventEmitted: true } }, { status: 201 });
  throw new Error(`Unexpected request: ${method ?? 'GET'} ${url}`);
}); }

describe('Announcement detail', () => {
  it('removes School-wide and arbitrary Class choices from Teacher target controls', async () => { const otherClass = { ...schoolClass, id: crypto.randomUUID(), name: 'Unassigned Class' }; vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json({ data: [] })); renderAnnouncements(<AnnouncementTargets schoolId="school" announcementId={announcementId} version={version} years={[year]} classes={[schoolClass, otherClass]} teacherClassIds={new Set([classId])} editable />); await screen.findByText('No targets are attached to this Version.'); expect(screen.queryByRole('option', { name: 'SCHOOL' })).not.toBeInTheDocument(); await userEvent.selectOptions(screen.getByLabelText('Academic Year'), yearId); expect(screen.getByRole('option', { name: 'Class A' })).toBeInTheDocument(); expect(screen.queryByRole('option', { name: 'Unassigned Class' })).not.toBeInTheDocument(); });
  it('renders immutable historical content and creates a new Version through the dedicated endpoint', async () => { const fetchMock = setup(); renderAnnouncements(<AnnouncementDetailWorkspace announcementId={announcementId} />); expect((await screen.findAllByText('The School will close tomorrow.')).length).toBeGreaterThan(0); await userEvent.click(screen.getByRole('button', { name: 'New Version' })); const body = screen.getByLabelText('Body'); await userEvent.clear(body); await userEvent.type(body, 'Updated plain text'); await userEvent.click(screen.getByRole('button', { name: 'Create new Version' })); await waitFor(() => expect(fetchMock.mock.calls.some(([url, init]) => String(url).endsWith('/versions') && (init as RequestInit).method === 'POST')).toBe(true)); const call = fetchMock.mock.calls.find(([url, init]) => String(url).endsWith('/versions') && (init as RequestInit).method === 'POST'); expect(JSON.parse(String((call?.[1] as RequestInit).body))).toEqual({ title: 'School closure', body: 'Updated plain text' }); expect(fetchMock.mock.calls.some(([url, init]) => String(url).includes(versionId) && (init as RequestInit | undefined)?.method === 'PATCH')).toBe(false); });
  it('adds an exact CLASS/PARENTS target without recipient or School identifiers', async () => { const fetchMock = setup(); renderAnnouncements(<AnnouncementDetailWorkspace announcementId={announcementId} />); await screen.findByText('No targets are attached to this Version.'); await userEvent.selectOptions(screen.getByLabelText('Academic Year'), yearId); await userEvent.selectOptions(screen.getByLabelText('Class'), classId); await userEvent.click(screen.getByRole('button', { name: 'Add target' })); await waitFor(() => expect(fetchMock.mock.calls.some(([url, init]) => String(url).endsWith('/targets') && (init as RequestInit).method === 'POST')).toBe(true)); const call = fetchMock.mock.calls.find(([url, init]) => String(url).endsWith('/targets') && (init as RequestInit).method === 'POST'); const payload = JSON.parse(String((call?.[1] as RequestInit).body)); expect(payload).toEqual({ announcementVersionId: versionId, targets: [{ audience: 'PARENTS', targetType: 'CLASS', academicYearId: yearId, classId }] }); expect(JSON.stringify(payload)).not.toMatch(/schoolId|recipientUserId/); });
  it('requires publish confirmation, sends the exact Version, and calls no Notification or Outbox API', async () => { const fetchMock = setup(); renderAnnouncements(<AnnouncementDetailWorkspace announcementId={announcementId} />); await screen.findByText('Publication actions'); await userEvent.click(screen.getByRole('button', { name: 'Publish now' })); expect(screen.getByText(/Recipients will be resolved now/)).toBeInTheDocument(); expect(fetchMock.mock.calls.some(([url, init]) => String(url).endsWith('/publish') && (init as RequestInit | undefined)?.method === 'POST')).toBe(false); await userEvent.click(screen.getByRole('button', { name: 'Confirm' })); await waitFor(() => expect(screen.getByText('Announcement published. Notifications are processed asynchronously.')).toBeInTheDocument()); const call = fetchMock.mock.calls.find(([url, init]) => String(url).endsWith('/publish') && (init as RequestInit).method === 'POST'); const payload = JSON.parse(String((call?.[1] as RequestInit).body)); expect(payload.announcementVersionId).toBe(versionId); expect(payload.idempotencyKey).toMatch(/^[0-9a-f-]{36}$/i); expect(payload).not.toHaveProperty('recipients'); expect(fetchMock.mock.calls.some(([url]) => /notifications|outbox/.test(String(url)))).toBe(false); });
  it('schedules with an exact ISO instant and states that recipients resolve at actual publication time', async () => { const fetchMock = setup(); renderAnnouncements(<AnnouncementDetailWorkspace announcementId={announcementId} />); await screen.findByText('Publication actions'); await userEvent.click(screen.getByRole('button', { name: 'Schedule' })); expect(screen.getAllByText(/Recipients are determined at actual publication time/).length).toBeGreaterThan(0); await userEvent.type(screen.getByLabelText('Publication date and time'), '2027-01-02T10:30'); const scheduleButtons = screen.getAllByRole('button', { name: 'Schedule' }); await userEvent.click(scheduleButtons.at(-1)!); await waitFor(() => expect(fetchMock.mock.calls.some(([url, init]) => String(url).endsWith('/publish') && (init as RequestInit).method === 'POST')).toBe(true)); const call = fetchMock.mock.calls.find(([url, init]) => String(url).endsWith('/publish') && (init as RequestInit).method === 'POST'); const payload = JSON.parse(String((call?.[1] as RequestInit).body)); expect(payload.announcementVersionId).toBe(versionId); expect(payload.scheduledAt).toBe(new Date('2027-01-02T10:30').toISOString()); expect(payload).not.toHaveProperty('recipients'); });
});
