import { screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AnnouncementsWorkspace } from '@/components/announcements/announcements-workspace';
import { announcement, announcementId, page, renderAnnouncements } from './test-helpers';

const navigation = vi.hoisted(() => ({ search: '', replace: vi.fn(), push: vi.fn() }));
vi.mock('next/navigation', () => ({ usePathname: () => '/announcements', useRouter: () => ({ replace: navigation.replace, push: navigation.push }), useSearchParams: () => new URLSearchParams(navigation.search) }));
afterEach(() => { vi.restoreAllMocks(); navigation.search = ''; navigation.replace.mockReset(); navigation.push.mockReset(); });

describe('Announcements workspace', () => {
  it('uses server filters and the optimized latestVersion list contract without Version N+1', async () => { navigation.search = 'status=DRAFT&audience=PARENTS&targetType=CLASS&search=closure'; const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json(page([announcement]))); renderAnnouncements(<AnnouncementsWorkspace />); expect(await screen.findByText('School closure')).toBeInTheDocument(); const calls = fetchMock.mock.calls.map(([url]) => String(url)); expect(calls[0]).toContain('status=DRAFT'); expect(calls[0]).toContain('audience=PARENTS'); expect(calls[0]).toContain('targetType=CLASS'); expect(calls[0]).toContain('search=closure'); expect(calls.some((url) => url.includes(`/announcements/${announcementId}/versions`))).toBe(false); });
  it('creates only an initial plain-text payload with no School, recipients, notification, or publication fields', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input, init) => { const url = String(input); if (url.startsWith('/api/v1/announcements?')) return Response.json(page([announcement])); if (url === '/api/v1/announcements' && (init as RequestInit).method === 'POST') return Response.json({ data: { announcement: { ...announcement, latestVersion: undefined }, version: announcement.latestVersion } }, { status: 201 }); throw new Error(`Unexpected ${url}`); }); renderAnnouncements(<AnnouncementsWorkspace />); await screen.findByText('School closure'); await userEvent.click(screen.getByRole('button', { name: 'Create Announcement' })); await userEvent.type(screen.getByLabelText('Title'), ' Notice '); await userEvent.type(screen.getByLabelText('Body'), '<b>plain</b>'); const buttons = screen.getAllByRole('button', { name: 'Create Announcement' }); await userEvent.click(buttons.at(-1)!); await waitFor(() => expect(navigation.push).toHaveBeenCalledWith(`/announcements/${announcementId}`)); const call = fetchMock.mock.calls.find(([url, init]) => String(url) === '/api/v1/announcements' && (init as RequestInit).method === 'POST'); const payload = JSON.parse(String((call?.[1] as RequestInit).body)); expect(payload).toEqual({ title: 'Notice', body: '<b>plain</b>' }); expect(JSON.stringify(payload)).not.toMatch(/schoolId|recipient|notification|publication/i); });
  it('denies Parent management before making a request', () => { const fetchMock = vi.spyOn(globalThis, 'fetch'); renderAnnouncements(<AnnouncementsWorkspace />, 'PARENT'); expect(screen.getByText('Access unavailable')).toBeInTheDocument(); expect(fetchMock).not.toHaveBeenCalled(); });
});
