'use client';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Button } from '@school/ui';
import { Field, InlineFeedback, SectionHeader, selectClassName } from '@/components/academic/ui';
import { announcementsApi } from '@/lib/frontend/announcements/api';
import { announcementCopy as t } from '@/lib/frontend/announcements/copy';
import { announcementErrorMessage, mapAnnouncementValidation } from '@/lib/frontend/announcements/errors';
import { invalidateAnnouncement } from '@/lib/frontend/announcements/mutations';
import { announcementKeys } from '@/lib/frontend/announcements/queries';
import { announcementAudiences, announcementTargetSchema, type AnnouncementTargetValues } from '@/lib/frontend/announcements/schemas';
import type { AnnouncementVersionDto } from '@/lib/frontend/announcements/types';
import type { AcademicYearDto, ClassDto } from '@/lib/frontend/academic/types';

export function AnnouncementTargets({ schoolId, announcementId, version, years, classes, teacherClassIds, editable }: { schoolId: string; announcementId: string; version: AnnouncementVersionDto; years: AcademicYearDto[]; classes: ClassDto[]; teacherClassIds?: Set<string>; editable: boolean }) {
  const queryClient = useQueryClient(); const [error, setError] = useState<string>(); const query = useQuery({ queryKey: announcementKeys.targets(schoolId, announcementId, version.id), queryFn: () => announcementsApi.targets(announcementId, version.id) });
  const form = useForm<AnnouncementTargetValues>({ resolver: zodResolver(announcementTargetSchema), defaultValues: { audience: 'PARENTS', targetType: 'CLASS', academicYearId: '', classId: '' } }); const targetType = form.watch('targetType'); const yearId = form.watch('academicYearId');
  const eligibleYears = years.filter((year) => year.status === 'ACTIVE'); const eligibleClasses = classes.filter((item) => item.status === 'ACTIVE' && (!yearId || item.academicYearId === yearId) && (!teacherClassIds || teacherClassIds.has(item.id)));
  const mutation = useMutation({ mutationFn: (value: AnnouncementTargetValues) => announcementsApi.addTargets(announcementId, version.id, [{ audience: value.audience, targetType: value.targetType, academicYearId: value.academicYearId, ...(value.targetType === 'CLASS' ? { classId: value.classId } : {}) }]), onSuccess: async () => { await invalidateAnnouncement(queryClient, schoolId, announcementId, { list: true, targets: true }); setError(undefined); }, onError: (value) => { if (!mapAnnouncementValidation(value, form.setError)) setError(announcementErrorMessage(value)); } });
  return <section className="space-y-4 rounded-lg border bg-card p-5"><SectionHeader title={t.targets} description={teacherClassIds ? t.teacherScope : t.targetHint} />{error ? <InlineFeedback kind="error">{error}</InlineFeedback> : null}<ul className="grid gap-2 sm:grid-cols-2">{query.data?.map((target) => { const className = target.classId ? classes.find((item) => item.id === target.classId)?.name ?? t.class : t.wholeSchool; return <li key={target.id} className="rounded-md border p-3 text-sm"><span className="font-medium">{target.audience}</span><span className="mx-2 text-muted-foreground">·</span>{target.targetType}: {className}</li>; })}</ul>{query.isSuccess && query.data.length === 0 ? <p className="text-sm text-muted-foreground">{t.noTargets}</p> : null}
    {editable ? <form className="grid gap-3 border-t pt-4 sm:grid-cols-2" noValidate onSubmit={form.handleSubmit((value) => mutation.mutate(value))}><Field label={t.audience} htmlFor="announcement-audience" error={form.formState.errors.audience?.message}><select id="announcement-audience" className={selectClassName} {...form.register('audience')}>{announcementAudiences.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label={t.targetType} htmlFor="announcement-target-type" error={form.formState.errors.targetType?.message}><select id="announcement-target-type" className={selectClassName} {...form.register('targetType', { onChange: () => form.setValue('classId', '') })}>{teacherClassIds ? <option value="CLASS">CLASS</option> : <><option value="CLASS">CLASS</option><option value="SCHOOL">SCHOOL</option></>}</select></Field><Field label={t.academicYear} htmlFor="announcement-year" error={form.formState.errors.academicYearId?.message}><select id="announcement-year" className={selectClassName} {...form.register('academicYearId', { onChange: () => form.setValue('classId', '') })}><option value="">{t.selectYear}</option>{eligibleYears.map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</select></Field>{targetType === 'CLASS' ? <Field label={t.class} htmlFor="announcement-class" error={form.formState.errors.classId?.message}><select id="announcement-class" className={selectClassName} disabled={!yearId} {...form.register('classId')}><option value="">{t.selectClass}</option>{eligibleClasses.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field> : <input type="hidden" {...form.register('classId')} />}<div className="sm:col-span-2"><Button type="submit" disabled={mutation.isPending}>{t.addTarget}</Button></div></form> : <p className="border-t pt-4 text-sm text-muted-foreground">{t.targetHint}</p>}
  </section>;
}
