export const parentPortalCopy = {
  dashboardTitle: 'Family workspace',
  dashboardDescription: 'Your current related children and persisted school notifications.',
  myChildren: 'My children',
  childrenDescription: 'Children returned by your active Parent profiles and current relationships in this school.',
  relatedChildren: 'Related children',
  dashboardOverview: 'Family overview',
  unreadNotifications: 'Unread notifications',
  notifications: 'Notifications',
  notificationsDescription: (count: number | undefined) => count === undefined
    ? 'Open your persisted notification inbox.'
    : `${count} unread notification${count === 1 ? '' : 's'}.`,
  viewAllChildren: 'View all children',
  viewChild: (name: string) => `View ${name}`,
  studentCode: 'Student code',
  unknown: '—',
  loading: 'Loading your family workspace…',
  childrenLoading: 'Loading your children…',
  unavailable: 'Family workspace unavailable',
  unavailableDescription: 'Your Parent profiles and current child relationships could not be loaded. Please try again.',
  noProfile: 'No active parent profile',
  noProfileDescription: 'No active parent profile is linked to your account for this school.',
  noChildren: 'No active child relationships',
  noChildrenDescription: 'No active child relationships are currently available.',
  backToChildren: 'Back to My children',
  childUnavailable: 'Child unavailable',
  childUnavailableDescription: 'This child is unavailable or outside your current access.',
  overview: 'Overview',
  academicPlacement: 'Academic placement',
  academicYear: 'Academic Year',
  chooseAcademicYear: 'Choose an Academic Year',
  viewAcademicYear: 'View academic context',
  noAcademicYears: 'No academic history is available for this child.',
  selectAcademicYear: 'Select one of this child’s Academic Years to view placement and published results.',
  placementUnavailable: 'No active placement is available for this Academic Year.',
  classLabel: 'Class', stageLabel: 'Stage', levelLabel: 'Level', trackLabel: 'Track',
  homework: 'Homework',
  homeworkUnavailable: 'Homework list discovery is not currently available for parent accounts.',
  homeworkExplanation: 'A known authorized Homework link remains readable through the existing read-only detail, but this portal does not fetch the staff Homework list.',
  results: 'Published results',
  subjectResults: 'Subject results', periodResults: 'Period results', annualResults: 'Annual results',
  noPublishedResults: 'No published results are available.',
  publishedRevision: 'Published revision',
  academicDataUnavailable: 'Academic information unavailable',
  academicDataUnavailableDescription: 'Placement and published results could not be loaded. Please try again.',
  noManagement: 'This portal does not expose Grade, Result, Homework, or Announcement management actions.',
} as const;
