export const parentCopy = {
  title: 'Parents', description: 'Manage Parent profiles and historical Student relationships.', childrenTitle: 'My children', childrenDescription: 'Current children are grouped under each ACTIVE Parent profile linked to your account.',
  createParent: 'Create Parent', editParent: 'Edit Parent', parentCreated: 'Parent profile created. Student relationships are added separately.', firstName: 'First name', lastName: 'Last name', parentCode: 'Parent code', optional: 'Optional', status: 'Status', actions: 'Actions',
  searchLabel: 'Search Parents by name or code', search: 'Search', clear: 'Clear', filterStatus: 'Filter by status', allStatuses: 'All statuses', profile: 'Profile', linkedAccount: 'Linked account', linked: 'Linked to an existing school User', unlinked: 'No account linked',
  linkedHint: 'Account access is provisioned by email. The server derives the PARENT role and current School.', inviteAccount: 'Invite account', accountInvited: 'Parent account access was provisioned.',
  openParent: (name: string) => `Open ${name}`, backToParents: 'Back to Parents', edit: 'Edit', loadingParents: 'Loading Parents…', loadingParent: 'Loading Parent…', loadingChildren: 'Loading children…', listError: 'Parents could not be loaded.', unavailable: 'Parent unavailable', unavailableDescription: 'This Parent is unavailable or outside your current access.',
  relationshipHistory: 'Student relationships', relationshipDescription: 'ACTIVE and ENDED relationships remain independent from the Parent profile lifecycle.', student: 'Student', studentCode: 'Student code', linkedOn: 'Linked on', createRelationship: 'Link Student', endRelationship: 'End relationship', relationshipSeparate: 'This links a Student to the Parent profile only. It does not change Student enrollment or Parent account role.',
  studentSearch: 'Search Students by name or code', selectStudent: 'Select a Student', noEligibleStudents: 'No eligible ACTIVE or INACTIVE Students were found on this page.', duplicateSelection: 'This Student already has an ACTIVE relationship with the Parent.',
  endTitle: 'End Student relationship?', endDescription: 'Future child access will end. Existing historical publications and notifications remain unchanged.', historicalStable: 'The relationship row remains in administrator history and no Parent, Student, publication, or notification record is deleted.',
  inactiveScope: 'Inactive Parent profiles cannot access linked children. Existing relationship rows are not automatically ended.', changesSaved: 'Changes saved successfully.', relationshipsUpdated: 'Student relationships updated successfully.', save: 'Save changes', create: 'Create', confirmEnd: 'Confirm end relationship',
  lifecycleTitle: (action: string, name: string) => `${action} ${name}?`, lifecycleDescription: (status: string, name: string) => status === 'INACTIVE' ? `${name} will become INACTIVE. Child access stops, but relationship rows are not ended or deleted.` : `${name} will move to ${status}. Student relationship history will remain available.`,
  archive: 'Archive', activate: 'Reactivate', deactivate: 'Deactivate', noProfiles: 'No active Parent profiles', noProfilesDescription: 'Your account has no ACTIVE Parent profile linked in this School.', noChildren: 'No current children', noChildrenDescription: 'This profile has no ACTIVE Student relationships.', currentOnly: 'Only current ACTIVE relationships appear here. Full Parent portal features are deferred.', unknown: '—',
} as const;
