export const dashboardCopy = {
  teacherTitle: 'My teaching workspace',
  teacherDescription: 'Your active assignment context and shortcuts for this school.',
  loading: 'Loading your teaching workspace…',
  unavailable: 'Teaching workspace unavailable',
  unavailableDescription: 'Your current Teacher profile or assignments could not be loaded. Please try again.',
  referencesUnavailable: 'Assignment context unavailable',
  referencesUnavailableDescription: 'Academic Year, Class, or Subject labels could not be loaded. Please try again.',
  noProfile: 'No active teacher profile',
  noProfileDescription: 'No active teacher profile is linked to your account for this school.',
  noAssignments: 'No active teaching assignments',
  noAssignmentsDescription: 'No active teaching assignments are currently available.',
  profile: 'Teacher profile',
  profiles: 'Teacher profiles',
  activeAssignments: 'Active assignments',
  assignedClasses: 'Assigned classes',
  assignedSubjects: 'Assigned subjects',
  overview: 'Teaching overview',
  unreadNotifications: 'Unread notifications',
  unreadUnavailable: 'Unavailable',
  myClasses: 'My classes',
  myClassesDescription: 'Classes are grouped for navigation; each Subject assignment remains an independent server-authorized scope.',
  subjects: 'Subjects',
  effectiveFrom: 'Effective from',
  takeAttendance: 'Take attendance',
  openGradebooks: 'Open gradebooks',
  homework: 'Homework',
  myWork: 'My work',
  myWorkDescription: 'Open existing operational modules. Every destination rechecks your current scope.',
  announcements: 'Announcements',
  announcementsDescription: 'Create and manage only the class-scoped Announcements authorized by your active assignments.',
  notifications: 'Notifications',
  notificationDescription: (count: number | undefined) => count === undefined ? 'Open your persisted notification inbox.' : `${count} unread notification${count === 1 ? '' : 's'}.`,
  viewProfile: 'View my Teacher profile',
  homeworkFilterNote: 'Homework opens with the supported Academic Year and Class filters; Subject remains visible here because the Homework list has no Subject filter.',
  unavailableAcademicYear: 'Unavailable Academic Year',
  unavailableClass: 'Unavailable Class',
  unavailableSubject: 'Unavailable Subject',
  attendanceAction: (className: string) => `Take attendance for ${className}`,
  gradeAction: (subjectName: string, className: string) => `Open ${subjectName} gradebooks for ${className}`,
  homeworkAction: (subjectName: string, className: string) => `Open Homework for ${subjectName} in ${className}`,
} as const;
