export const homeworkCopy = {
  title: 'Homework', description: 'Create, target, publish, and review Homework within authoritative academic scope.', teacherDescription: 'Only Homework within your exact active Class, Subject, and Academic Year assignments is returned.',
  create: 'Create Homework', edit: 'Edit Homework', details: 'Open Homework', filters: 'Homework filters', search: 'Search Homework', allYears: 'All Academic Years', allClasses: 'All Classes', allStatuses: 'All statuses', dueFrom: 'Due from', dueTo: 'Due to', invalidRange: 'Due from must be on or before due to.',
  academicYear: 'Academic Year', academicPeriod: 'Academic Period', subject: 'Subject', dueDate: 'Due date', status: 'Status', actions: 'Actions', descriptionField: 'Description', plainText: 'Plain text only. Attachments and rich text are deferred.',
  dueInsideYear: 'Due date must fall inside the Academic Year.', dueInsidePeriod: 'Due date must fall inside the Academic Period.',
  selectYear: 'Select Academic Year', selectPeriod: 'Select Academic Period', selectSubject: 'Select Subject', titleField: 'Title', createSuccess: 'Homework created as DRAFT.', unavailable: 'Homework unavailable', loading: 'Loading Homework…', noHomework: 'No Homework matches these filters.',
  authorScopeMissing: 'Creation requires this signed-in User to have an ACTIVE linked Teacher profile and an ACTIVE matching Subject and Academic Year assignment. No Teacher can be selected on the client.',
  overview: 'Overview', author: 'Teacher author', targets: 'Class targets', addTargets: 'Add Class targets', targetsAdded: 'Class targets added.', targetHint: 'Targets are CLASS-only, may include multiple Classes, and cannot be removed through the committed API.', targetFrozen: 'Targets are frozen after publication. The committed API has no target deletion operation.', noTargets: 'No Classes are targeted yet.',
  publish: 'Publish', close: 'Close', archive: 'Archive', lifecycleTitle: (action: string) => `${action} Homework?`, publishDescription: 'Publishing makes the Homework operational, freezes its structure and targets, and requires at least one ACTIVE Class target.', closeDescription: 'Closing stops new submissions while preserving Homework and Submission history.', archiveDescription: 'Archiving is terminal and preserves all Homework history.',
  roster: 'Student and Submission roster', rosterHint: 'The server resolves historical eligibility from StudentEnrollment on the Homework due date.', student: 'Student', notSubmitted: 'Not submitted', submittedAt: 'Submitted at', submission: 'Submission', content: 'Submission content', createSubmission: 'Record Submission', viewSubmission: 'Open Submission', submissionSaved: 'Submission saved.',
  review: 'Mark reviewed', reviewDescription: 'Mark this Submission as reviewed. No Grade or Result is created.', return: 'Return for revision', resubmit: 'Resubmit returned work', reviewed: 'Reviewed', returnedHint: 'Returned work reuses the same logical Submission row when resubmitted.', lateOwned: 'On-time or LATE status is derived by the server using the School calendar.',
  parentBoundary: 'Broad Homework management is unavailable to Parents. Related-child Homework discovery belongs in the future child portal.', parentReadOnly: 'Related-child Homework', parentReadOnlyHint: 'This direct resource view is read-only and the server verifies current Parent relationship plus due-date historical eligibility.',
  noChildSubmissions: 'No related-child Submission is available for this Homework.', relatedChild: 'Related child', backToChildren: 'Back to Children', back: 'Back to Homework', retry: 'Retry', save: 'Save', cancel: 'Cancel',
} as const;
