export const teacherCopy = {
  title: 'Teachers', description: 'Manage Teacher profiles, account links, and historical academic scope.',
  selfTitle: 'My Teacher profiles', selfDescription: 'Inspect the Teacher profiles linked to your current account and their Assignment history.',
  readOnly: 'Read-only access', readOnlyDescription: 'Teachers can inspect only their own linked profiles and Assignment history.',
  createTeacher: 'Create Teacher', editTeacher: 'Edit Teacher', teacherCreated: 'Teacher profile created. Assignments are added separately.',
  firstName: 'First name', lastName: 'Last name', teacherCode: 'Teacher code', optional: 'Optional', status: 'Status', actions: 'Actions',
  searchLabel: 'Search Teachers by name or code', search: 'Search', clear: 'Clear', filterStatus: 'Filter by status', allStatuses: 'All statuses',
  profile: 'Profile', linkedAccount: 'Linked account', linked: 'Linked to an existing school User', unlinked: 'No account linked',
  linkedHint: 'Connect this Teacher profile to an existing ACTIVE school User. Linking does not change the User’s School role.',
  linkedLookupUnavailable: 'Eligible-account lookup is not available yet. Enter the existing application User UUID only when it is known through an approved administrative process.',
  userId: 'Application User UUID', openTeacher: (name: string) => `Open ${name}`, backToTeachers: 'Back to Teachers', edit: 'Edit',
  noTeachers: 'No Teacher profiles found', noTeachersDescription: 'Create the first Teacher profile when your School is ready.',
  noLinkedSelf: 'No linked Teacher profile', noLinkedSelfDescription: 'Your current account is not linked to a Teacher profile in this School.',
  loadingTeachers: 'Loading Teachers…', loadingTeacher: 'Loading Teacher…', listError: 'Teachers could not be loaded.',
  unavailable: 'Teacher unavailable', unavailableDescription: 'This Teacher is unavailable or outside your current access.',
  assignmentHistory: 'Assignment history', assignmentDescription: 'Assignments define exact Class, Subject, and Academic Year scope. ENDED rows remain historical.',
  academicYear: 'Academic Year', className: 'Class', subject: 'Subject', effectiveFrom: 'Effective from', effectiveUntil: 'Effective until', ongoing: 'Ongoing',
  createAssignment: 'Create Assignment', endAssignment: 'End Assignment', selectYear: 'Select an Academic Year', selectClass: 'Select a Class', selectSubject: 'Select a Subject',
  noClasses: 'No eligible ACTIVE Classes are available for this Academic Year.', noSubjects: 'No eligible ACTIVE Subjects are available.',
  assignmentSeparate: 'Teacher profile and academic scope are separate. This operation creates only an ACTIVE TeacherAssignment.',
  duplicateSelection: 'This exact Teacher, Academic Year, Class, and Subject Assignment is already ACTIVE.',
  endDescription: 'The Assignment will end on the selected inclusive date. Its historical row will remain available.',
  reassignmentSeparate: 'To change scope, end the old Assignment and create a new one as two explicit actions.',
  inactiveScope: 'Inactive Teachers cannot access assigned academic resources. Existing Assignment rows are not ended or deleted.',
  confirmEnd: 'Confirm end Assignment', save: 'Save changes', create: 'Create', confirm: 'Confirm',
  endDateBefore: 'End date must be on or after the Assignment start date.', changesSaved: 'Changes saved successfully.', assignmentsUpdated: 'Assignment history updated successfully.',
  historyEmptyDescription: 'Assignment records will appear here without replacing prior history.',
  lifecycleTitle: (action: string, name: string) => `${action} ${name}?`,
  lifecycleDescription: (status: string, name: string) => status === 'INACTIVE'
    ? `${name} will become INACTIVE. Operational scope disappears immediately, but Assignment history is not ended or deleted.`
    : `${name} will move to ${status}. Assignment history will remain available.`,
  archive: 'Archive', activate: 'Reactivate', deactivate: 'Deactivate', unknown: '—',
} as const;
