export const gradeCopy = {
  title: 'Gradebook setup',
  description: 'Manage exact grading contexts, Assessments, Grade entry, and server-calculated Results.',
  teacherDescription: 'Only Gradebooks inside your active Class, Subject, and Academic Year assignments are returned by the server.',
  readOnly: 'Read only',
  createGradebook: 'Create Gradebook',
  createDescription: 'Choose every part of the exact Gradebook context. These selections cannot be changed after creation.',
  noConfigurationVersions: 'No active grading configuration version is available.',
  noConfigurationVersionsDescription: 'A School administrator must activate a grading configuration and one of its versions before a Gradebook can be created.',
  configurationVersionsUnavailable: 'Eligible grading configuration versions could not be loaded.',
  retry: 'Retry',
  gradebooks: 'Gradebooks',
  noGradebooks: 'No Gradebooks found',
  noGradebooksDescription: 'No Gradebooks match the current School context and filters.',
  loading: 'Loading Gradebooks…',
  unavailable: 'Gradebooks are unavailable',
  unavailableDescription: 'The resource may not exist or may be outside your current access.',
  academicYear: 'Academic Year', period: 'Academic Period', class: 'Class', subject: 'Subject',
  configurationVersion: 'Grading Configuration Version', status: 'Status', name: 'Gradebook name', actions: 'Actions',
  optionalName: 'Gradebook name (optional)',
  selectYear: 'Select an Academic Year', selectPeriod: 'Select an Academic Period', selectClass: 'Select a Class', selectSubject: 'Select a Subject', selectConfigurationVersion: 'Select an exact version',
  versionLabel: (configuration: string, version: number) => `${configuration} — Version ${version}`,
  allYears: 'All Academic Years', allPeriods: 'All Academic Periods', allClasses: 'All Classes', allSubjects: 'All Subjects', allStatuses: 'All statuses',
  openDetail: (name: string) => `Open ${name}`,
  back: 'Back to Gradebooks',
  exactContext: 'Exact immutable context',
  exactContextDescription: 'These identifiers were fixed when the Gradebook was created and cannot be changed.',
  lifecycle: 'Lifecycle',
  open: 'Open', close: 'Close', archive: 'Archive',
  lifecycleTitle: (action: string) => `${action} Gradebook?`,
  lifecycleDescription: (status: string) => status === 'OPEN'
    ? 'Opening makes this Gradebook operational for workflows permitted by the server.'
    : status === 'CLOSED'
      ? 'Closing may stop further Grade and Assessment changes. Existing academic history remains available.'
      : 'Archiving is terminal and preserves this Gradebook and all related academic history.',
  assessments: 'Assessments',
  assessmentsDescription: 'Assessments remain separate from Gradebook lifecycle and from Homework records.',
  createAssessment: 'Create Assessment', editAssessment: 'Edit Assessment',
  titleField: 'Title', type: 'Type', maximumScore: 'Maximum score', weight: 'Assessment weight', date: 'Assessment date', optional: 'Optional',
  weightHint: 'Weight is Assessment metadata used by grading configuration logic. It is not a Subject coefficient.',
  decimalHint: 'Enter a positive decimal with up to two decimal places, such as 10, 10.5, or 12.25.',
  dateHint: (start: string, end: string) => `Optional. If supplied, the date must be from ${start} through ${end}.`,
  create: 'Create', save: 'Save changes', cancel: 'Cancel',
  publishedReadOnly: 'Published Assessment settings are read-only because calculation-relevant structure is locked.',
  archivedReadOnly: 'Archived Assessments are terminal and read-only.',
  gradebookReadOnly: 'Closed and archived Gradebooks do not permit Assessment mutation.',
  periodClosed: 'This Academic Period is CLOSED, so new Assessments cannot be created.',
  publish: 'Publish', publishTitle: 'Publish Assessment?', publishDescription: 'Publishing locks calculation-relevant Assessment settings.',
  archiveAssessment: 'Archive', archiveAssessmentTitle: 'Archive Assessment?', archiveAssessmentDescription: 'Archiving is historical and terminal. Existing Grades are not deleted.',
  unknown: 'Unavailable', none: '—', filters: 'Gradebook filters', clearFilters: 'Clear filters', allTypes: 'All types',
  assessmentStatusFilter: 'Assessment status', assessmentTypeFilter: 'Assessment type',
  previous: 'Previous', next: 'Next', page: 'Page',
  changesSaved: 'Changes saved.', assessmentCreated: 'Assessment created.',
  gradebookCreated: 'Gradebook created.',
  futureGradeEntry: 'Grade entry is deferred to Task 031.',
  resultsWorkspace: 'Results workspace',
  rawGrades: 'Persisted Grades',
  rawGradesDescription: 'Browse persisted Grade states across Students and Assessments. No averages are calculated in the browser.',
  noPersistedGrade: 'Not entered',
  enterGrades: 'Enter grades',
  gradeEntryTitle: (assessment: string) => `Enter grades — ${assessment}`,
  gradeEntryDescription: (maximum: string) => `Save one atomic batch for this page. VALID scores must be from 0 through ${maximum}.`,
  gradeState: 'Grade state', score: 'Score', student: 'Student', studentCode: 'Student code',
  selectState: 'Not entered',
  gradeStates: { VALID: 'Valid score', MISSING: 'Missing', ABSENT: 'Absent', EXCUSED: 'Excused' },
  scoreFor: (student: string) => `Score for ${student}`,
  stateFor: (student: string) => `Grade state for ${student}`,
  scoreRequired: 'A score is required when the Grade state is VALID.',
  scoreInvalid: 'Use a non-negative decimal with at most two decimal places.',
  scoreAboveMaximum: (maximum: string) => `Score must not exceed ${maximum}.`,
  noGradeChanges: 'Change at least one Student Grade before saving.',
  unsavedChanges: 'Unsaved changes',
  unsavedPrompt: 'Discard unsaved Grade changes?',
  gradeBatchSaved: 'Grades saved. Results were not recalculated automatically.',
  rosterLimit: 'Each page contains at most 100 Students, matching the atomic backend batch limit.',
  resultsTitle: 'Academic Results',
  resultsDescription: 'Browse and manage server-calculated Subject, Period, and Annual Results as separate resources.',
  subjectResults: 'Subject Results', periodResults: 'Period Results', annualResults: 'Annual Results',
  subjectResult: 'Subject Result', periodResult: 'Period Result', annualResult: 'Annual Result',
  calculatedValue: 'Calculated value', resultType: 'Result type',
  noResults: 'No Results found', noResultsDescription: 'No Results match the selected type and filters.',
  resultsUnavailable: 'Results are unavailable',
  calculateResult: 'Calculate Result', calculateSubject: 'Calculate Subject Result', calculatePeriod: 'Calculate Period Result', calculateAnnual: 'Calculate Annual Result',
  calculateDescription: 'The server uses authoritative Grades, configuration rules, and historical academic context. The browser performs no Result arithmetic.',
  selectGradebook: 'Select a Gradebook', selectStudent: 'Select a Student',
  selectAllContext: 'Select every required academic context field.',
  calculationSucceeded: 'Result calculated by the server.',
  incompleteCalculation: 'Calculation incomplete',
  coefficientHint: 'Period calculations resolve CurriculumSubject coefficients on the server. Coefficients are not editable here.',
  annualHint: 'Annual Results are calculated separately from Period Results; they are never derived from the latest Period in the browser.',
  resultDetail: 'Result detail', exactResultContext: 'Exact Result context',
  finalize: 'Finalize', finalizeTitle: 'Finalize Result?', finalizeDescription: 'Finalization locks this Result for publication and historical use.',
  publishResult: 'Publish Result', publishResultTitle: 'Publish Result?', publishResultDescription: 'Publication creates an immutable Result snapshot. Eligible Parent recipients are resolved by the backend and cannot be edited here.',
  reviseResult: 'Publish revision', reviseTitle: 'Recalculate and publish a revision?', reviseDescription: 'The server will atomically recalculate, finalize, and create a new immutable publication revision. Previous publications remain unchanged.',
  resultPublished: 'Result published. Notifications are processed asynchronously.',
  resultRevised: 'Result revision published. Previous publications remain unchanged; notifications are processed asynchronously.',
  resultFinalized: 'Result finalized.',
  publicationVersion: 'Publication version', publishedAt: 'Published at',
  publicationHistoryUnavailable: 'Result publication history read API is not currently exposed.',
  teacherResultsDescription: 'Subject Results are limited by your exact active Class, Subject, and Academic Year assignments. Period and Annual administration is unavailable to Teachers.',
  resultTypeLabels: { SUBJECT: 'Subject', PERIOD: 'Period', ANNUAL: 'Annual' },
  viewResult: 'View Result',
  backToGradebooks: 'Back to Gradebooks',
  typeLabels: { QUIZ: 'Quiz', TEST: 'Test', EXAM: 'Exam', ORAL: 'Oral', PROJECT: 'Project', HOMEWORK: 'Homework assessment' },
} as const;
