import { fireEvent, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { AssessmentForm } from '@/components/grades/assessment-form';
import { assessment, gradebookId, period, renderGrades } from './test-helpers';

afterEach(() => vi.restoreAllMocks());
describe('Assessment form contracts', () => {
  it('creates the exact payload while preserving decimal strings and optional date', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json({ data: assessment })); renderGrades(<AssessmentForm gradebookId={gradebookId} period={period} onCancel={vi.fn()} onSaved={vi.fn()} />); await userEvent.type(screen.getByLabelText('Title'), 'Quiz 1'); await userEvent.type(screen.getByLabelText('Maximum score'), '12.25'); await userEvent.clear(screen.getByLabelText('Assessment weight')); await userEvent.type(screen.getByLabelText('Assessment weight'), '10.5'); await userEvent.click(screen.getByRole('button', { name: 'Create' })); await waitFor(() => expect(fetchMock).toHaveBeenCalled()); expect(fetchMock).toHaveBeenCalledWith(`/api/v1/gradebooks/${gradebookId}/assessments`, expect.objectContaining({ method: 'POST', body: JSON.stringify({ title: 'Quiz 1', assessmentType: 'QUIZ', maximumScore: '12.25', weight: '10.5', assessmentDate: null }) })); });
  it('blocks zero and over-precision decimals client-side', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch'); renderGrades(<AssessmentForm gradebookId={gradebookId} period={period} onCancel={vi.fn()} onSaved={vi.fn()} />); await userEvent.type(screen.getByLabelText('Title'), 'Quiz'); await userEvent.type(screen.getByLabelText('Maximum score'), '0'); await userEvent.clear(screen.getByLabelText('Assessment weight')); await userEvent.type(screen.getByLabelText('Assessment weight'), '1.234'); await userEvent.click(screen.getByRole('button', { name: 'Create' })); expect(await screen.findAllByRole('alert')).toHaveLength(2); expect(fetchMock).not.toHaveBeenCalled(); });
  it('blocks an obvious date outside the exact Period', async () => { const fetchMock = vi.spyOn(globalThis, 'fetch'); renderGrades(<AssessmentForm gradebookId={gradebookId} period={period} onCancel={vi.fn()} onSaved={vi.fn()} />); await userEvent.type(screen.getByLabelText('Title'), 'Quiz'); await userEvent.type(screen.getByLabelText('Maximum score'), '20'); fireEvent.change(screen.getByLabelText('Assessment date (Optional)'), { target: { value: '2027-01-01' } }); await userEvent.click(screen.getByRole('button', { name: 'Create' })); expect(await screen.findByRole('alert')).toHaveTextContent(/2026-09-01 through 2026-12-20/); expect(fetchMock).not.toHaveBeenCalled(); });
  it('maps existing-Grade structural conflicts without exposing backend text', async () => { vi.spyOn(globalThis, 'fetch').mockResolvedValue(Response.json({ error: { code: 'BUSINESS_RULE_VIOLATION', featureCode: 'ASSESSMENT_NOT_EDITABLE', message: 'internal grade row detail' } }, { status: 422 })); renderGrades(<AssessmentForm gradebookId={gradebookId} period={period} initial={assessment} onCancel={vi.fn()} onSaved={vi.fn()} />); await userEvent.click(screen.getByRole('button', { name: 'Save changes' })); const alert = await screen.findByRole('alert'); expect(alert).toHaveTextContent(/grades already depend/); expect(alert).not.toHaveTextContent('internal grade row detail'); });
});
