import { QueryClient } from '@tanstack/react-query';
import { describe, expect, it, vi } from 'vitest';
import { gradeKeys, invalidateAfterGradeSave, invalidateGradebook, invalidateResult } from '@/lib/frontend/grades/queries';
import { gradebookId, schoolId } from './test-helpers';

describe('Grade tenant query keys and invalidation', () => {
  it('separates School, configuration-version, list, detail, and exact Assessment caches', () => { expect(gradeKeys.gradebookList(schoolId, { page: 1, pageSize: 20 })).not.toEqual(gradeKeys.gradebookList('school-b', { page: 1, pageSize: 20 })); expect(gradeKeys.configurationVersions(schoolId)).not.toEqual(gradeKeys.configurationVersions('school-b')); expect(gradeKeys.assessmentList(schoolId, gradebookId, { page: 1, pageSize: 20 })).toEqual(['grades', schoolId, 'gradebooks', gradebookId, 'assessments', { page: 1, pageSize: 20 }]); });
  it('invalidates only relevant Gradebook and Assessment boundaries', async () => { const client = new QueryClient(); const invalidate = vi.spyOn(client, 'invalidateQueries').mockResolvedValue(); const clear = vi.spyOn(client, 'clear'); await invalidateGradebook(client, schoolId, gradebookId, true); expect(invalidate).toHaveBeenCalledWith({ queryKey: gradeKeys.gradebookDetail(schoolId, gradebookId) }); expect(invalidate).toHaveBeenCalledWith({ queryKey: gradeKeys.assessments(schoolId, gradebookId) }); expect(invalidate).toHaveBeenCalledWith({ queryKey: gradeKeys.gradebooks(schoolId) }); expect(clear).not.toHaveBeenCalled(); });
  it('invalidates raw Grades and Results after a Grade save without clearing the cache', async () => { const client = new QueryClient(); const invalidate = vi.spyOn(client, 'invalidateQueries').mockResolvedValue(); const clear = vi.spyOn(client, 'clear'); await invalidateAfterGradeSave(client, schoolId, gradebookId); expect(invalidate).toHaveBeenCalledWith({ queryKey: gradeKeys.gradeMatrices(schoolId, gradebookId) }); expect(invalidate).toHaveBeenCalledWith({ queryKey: gradeKeys.results(schoolId) }); expect(clear).not.toHaveBeenCalled(); });
  it('keeps Result type/detail invalidation current-School scoped', async () => { const client = new QueryClient(); const invalidate = vi.spyOn(client, 'invalidateQueries').mockResolvedValue(); await invalidateResult(client, schoolId, 'SUBJECT', 'result'); expect(invalidate).toHaveBeenCalledWith({ queryKey: gradeKeys.resultType(schoolId, 'SUBJECT') }); expect(invalidate).toHaveBeenCalledWith({ queryKey: gradeKeys.resultDetail(schoolId, 'SUBJECT', 'result') }); expect(gradeKeys.results(schoolId)).not.toEqual(gradeKeys.results('school-b')); });
});
