'use client';
import { useQuery, useQueryClient } from '@tanstack/react-query'; import { Plus, Search } from 'lucide-react'; import { usePathname, useRouter, useSearchParams } from 'next/navigation'; import { useCallback, useState } from 'react'; import { Button } from '@school/ui'; import { InlineFeedback, Modal, inputClassName, selectClassName } from '@/components/academic/ui'; import { AccessDeniedWithReturn } from '@/components/app/route-access'; import { useAppContext } from '@/components/app/app-context'; import { ApiErrorState } from '@/components/ui/states'; import { can } from '@/lib/frontend/permissions'; import { parentsApi } from '@/lib/frontend/parents/api'; import { parentCopy as t } from '@/lib/frontend/parents/copy'; import { parentKeys } from '@/lib/frontend/parents/queries'; import type { ParentDto, ParentStatus } from '@/lib/frontend/parents/types'; import { ParentForm } from './parent-form'; import { ParentsTable } from './parents-table';
const statuses: readonly ParentStatus[] = ['ACTIVE', 'INACTIVE', 'ARCHIVED'];
export function ParentsWorkspace() {
  const context = useAppContext(); const role = context.currentSchool?.role; const schoolId = context.currentSchool?.id; const searchParams = useSearchParams(); const pathname = usePathname(); const router = useRouter(); const queryClient = useQueryClient(); const [editing, setEditing] = useState<ParentDto | null | undefined>(); const [notice, setNotice] = useState<string>();
  const pageValue = Number(searchParams.get('page') ?? '1'); const page = Number.isInteger(pageValue) && pageValue > 0 ? pageValue : 1; const rawStatus = searchParams.get('status'); const status = statuses.includes(rawStatus as ParentStatus) ? rawStatus as ParentStatus : undefined; const search = searchParams.get('search') || undefined; const [searchDraft, setSearchDraft] = useState(search ?? '');
  const updateUrl = useCallback((updates: Record<string, string | number | undefined>) => { const next = new URLSearchParams(searchParams.toString()); for (const [key, value] of Object.entries(updates)) if (value === undefined || value === '') next.delete(key); else next.set(key, String(value)); const suffix = next.toString(); router.replace(`${pathname}${suffix ? `?${suffix}` : ''}`, { scroll: false }); }, [pathname, router, searchParams]);
  const allowed = !!role && !!schoolId && (role === 'SCHOOL_ADMIN' || role === 'SUPER_ADMIN') && can(role, 'parents.manage'); const params = { page, pageSize: 20, status, search }; const query = useQuery({ queryKey: parentKeys.list(schoolId ?? 'no-school', params), queryFn: () => parentsApi.list(params), enabled: allowed }); if (!allowed || !schoolId) return <AccessDeniedWithReturn />;
  const saved = async () => { await queryClient.invalidateQueries({ queryKey: parentKeys.lists(schoolId) }); setNotice(editing ? t.changesSaved : t.parentCreated); setEditing(undefined); };
  return <div className="mx-auto max-w-[100rem] space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">{t.title}</h1><p className="mt-1 text-sm text-muted-foreground">{t.description}</p></div><Button type="button" onClick={() => setEditing(null)}><Plus className="size-4" />{t.createParent}</Button></header>{notice ? <InlineFeedback kind="success">{notice}</InlineFeedback> : null}<div className="flex flex-col gap-2 sm:flex-row"><form className="flex flex-1 gap-2" onSubmit={(event) => { event.preventDefault(); updateUrl({ search: searchDraft.trim() || undefined, page: 1 }); }}><label className="sr-only" htmlFor="parent-search">{t.searchLabel}</label><input id="parent-search" className={inputClassName} value={searchDraft} placeholder={t.searchLabel} onChange={(event) => setSearchDraft(event.target.value)} /><Button type="submit" variant="outline"><Search className="size-4" />{t.search}</Button>{search ? <Button type="button" variant="ghost" onClick={() => { setSearchDraft(''); updateUrl({ search: undefined, page: 1 }); }}>{t.clear}</Button> : null}</form><select aria-label={t.filterStatus} className={`${selectClassName} sm:w-56`} value={status ?? ''} onChange={(event) => updateUrl({ status: event.target.value || undefined, page: 1 })}><option value="">{t.allStatuses}</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select></div>{query.isError ? <ApiErrorState title={t.listError} onRetry={() => void query.refetch()} /> : <ParentsTable result={query.data} loading={query.isPending} onEdit={setEditing} onPage={(next) => updateUrl({ page: next })} />}<Modal open={editing !== undefined} title={editing ? t.editParent : t.createParent} description={t.linkedHint} onClose={() => setEditing(undefined)}>{editing !== undefined ? <ParentForm initial={editing ?? undefined} onCancel={() => setEditing(undefined)} onSaved={saved} /> : null}</Modal></div>;
}
