'use client';

import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ChevronRight, Pencil, Plus } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@school/ui';
import { ApiErrorState } from '@/components/ui/states';
import { academicApi } from '@/lib/frontend/academic/api';
import { academicCopy as t } from '@/lib/frontend/academic/copy';
import { academicKeys } from '@/lib/frontend/academic/queries';
import type { CurriculumDto, CurriculumSubjectDto, CurriculumVersionDto, SubjectDto } from '@/lib/frontend/academic/types';
import { CurriculumForm, CurriculumSubjectForm, VersionForm } from './forms';
import { activeTransitions, curriculumTransitions, LifecycleActions, versionTransitions } from './lifecycle-actions';
import { EmptyTableRow, InlineFeedback, Modal, Pagination, SectionHeader, StatusBadge, TableShell, selectClassName } from './ui';

export function CurriculaSection({ schoolId, canManage, page, status, onPage, onStatus }: { schoolId: string; canManage: boolean; page: number; status?: string; onPage: (page: number) => void; onStatus: (status?: string) => void }) {
  const queryClient = useQueryClient();
  const [editing, setEditing] = useState<CurriculumDto | null | undefined>();
  const [selected, setSelected] = useState<CurriculumDto>();
  const [notice, setNotice] = useState<string>();
  const params = { page, pageSize: 20, status };
  const query = useQuery({ queryKey: academicKeys.list(schoolId, 'curricula', params), queryFn: () => academicApi.curricula(params) });
  const invalidate = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['academic', schoolId, 'curricula'] }), queryClient.invalidateQueries({ queryKey: academicKeys.selectors(schoolId, 'curricula') }), queryClient.invalidateQueries({ queryKey: academicKeys.selectors(schoolId, 'versions') })]); setNotice(t.mutationSuccess); };
  return <div className="space-y-6"><SectionHeader title={t.sections.curricula} description="Curricula contain named historical versions; versions contain contextual subject coefficients." action={canManage ? <Button type="button" onClick={() => setEditing(null)}><Plus className="size-4" aria-hidden="true" />{t.createCurriculum}</Button> : undefined} />{notice ? <InlineFeedback kind="success">{notice}</InlineFeedback> : null}<label className="block max-w-xs"><span className="sr-only">{t.filterStatus}</span><select aria-label={t.filterStatus} value={status ?? ''} className={selectClassName} onChange={(event) => onStatus(event.target.value || undefined)}><option value="">{t.allStatuses}</option>{['ACTIVE', 'INACTIVE', 'ARCHIVED'].map((value) => <option key={value} value={value}>{value}</option>)}</select></label>{query.isError ? <ApiErrorState title={t.listError} onRetry={() => void query.refetch()} /> : <><TableShell headers={[t.name, t.status, t.actions]} loading={query.isPending}>{query.data?.data.length === 0 ? <EmptyTableRow columns={3} /> : query.data?.data.map((curriculum) => <tr key={curriculum.id}><td className="px-4 py-3 font-medium">{curriculum.name}</td><td className="px-4 py-3"><StatusBadge status={curriculum.status} /></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button type="button" size="sm" variant="outline" onClick={() => setSelected(curriculum)}>{t.versions}<ChevronRight className="size-4" aria-hidden="true" /></Button>{canManage ? <><Button type="button" variant="ghost" size="sm" aria-label={`${t.edit} ${curriculum.name}`} onClick={() => setEditing(curriculum)}><Pencil className="size-4" aria-hidden="true" /></Button><LifecycleActions resourceName={curriculum.name} path={`/api/v1/curricula/${curriculum.id}`} transitions={curriculumTransitions(curriculum.status)} onSaved={invalidate} /></> : null}</div></td></tr>)}</TableShell>{query.data ? <Pagination {...query.data.meta} onPage={onPage} /> : null}</>}{selected ? <VersionsPanel schoolId={schoolId} curriculum={selected} canManage={canManage} onClose={() => setSelected(undefined)} /> : <p className="rounded-md border border-dashed p-6 text-center text-sm text-muted-foreground">{t.selectCurriculum}</p>}<Modal open={editing !== undefined} title={editing ? t.editCurriculum : t.createCurriculum} onClose={() => setEditing(undefined)}>{editing !== undefined ? <CurriculumForm initial={editing ?? undefined} onCancel={() => setEditing(undefined)} onSaved={async () => { await invalidate(); setEditing(undefined); }} /> : null}</Modal></div>;
}

function VersionsPanel({ schoolId, curriculum, canManage, onClose }: { schoolId: string; curriculum: CurriculumDto; canManage: boolean; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [page, setPage] = useState(1);
  const [editing, setEditing] = useState<CurriculumVersionDto | null | undefined>();
  const [selected, setSelected] = useState<CurriculumVersionDto>();
  const [notice, setNotice] = useState<string>();
  const params = { page, pageSize: 20 };
  const query = useQuery({ queryKey: academicKeys.versions(schoolId, curriculum.id, params), queryFn: () => academicApi.versions(curriculum.id, params) });
  const invalidate = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['academic', schoolId, 'versions', curriculum.id] }), queryClient.invalidateQueries({ queryKey: academicKeys.selectors(schoolId, 'versions') })]); setNotice(t.mutationSuccess); };
  return <section className="space-y-4 rounded-lg border bg-muted/20 p-4"><SectionHeader title={`${t.versions} — ${curriculum.name}`} description="Version names are the committed per-Curriculum identity; no numeric version counter is used." action={<div className="flex gap-2">{canManage && curriculum.status !== 'ARCHIVED' ? <Button type="button" size="sm" onClick={() => setEditing(null)}><Plus className="size-4" aria-hidden="true" />{t.createVersion}</Button> : null}<Button type="button" size="sm" variant="outline" onClick={onClose}>{t.cancel}</Button></div>} />{notice ? <InlineFeedback kind="success">{notice}</InlineFeedback> : null}{query.isError ? <ApiErrorState title={t.listError} onRetry={() => void query.refetch()} /> : <><TableShell headers={[t.name, t.status, t.actions]} loading={query.isPending}>{query.data?.data.length === 0 ? <EmptyTableRow columns={3} /> : query.data?.data.map((version) => <tr key={version.id}><td className="px-4 py-3 font-medium">{version.name}</td><td className="px-4 py-3"><StatusBadge status={version.status} /></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button type="button" variant="outline" size="sm" onClick={() => setSelected(version)}>{t.curriculumSubjects}</Button>{canManage ? <><Button type="button" variant="ghost" size="sm" aria-label={`${t.edit} ${version.name}`} onClick={() => setEditing(version)}><Pencil className="size-4" aria-hidden="true" /></Button><LifecycleActions resourceName={version.name} path={`/api/v1/curriculum-versions/${version.id}`} transitions={versionTransitions(version.status)} onSaved={invalidate} /></> : null}</div></td></tr>)}</TableShell>{query.data ? <Pagination {...query.data.meta} onPage={setPage} /> : null}</>}{selected ? <CurriculumSubjectsPanel schoolId={schoolId} version={selected} canManage={canManage} onClose={() => setSelected(undefined)} /> : <p className="rounded-md border border-dashed p-4 text-center text-sm text-muted-foreground">{t.selectVersion}</p>}<Modal open={editing !== undefined} title={editing ? t.editVersion : t.createVersion} onClose={() => setEditing(undefined)}>{editing !== undefined ? <VersionForm curriculumId={curriculum.id} initial={editing ?? undefined} onCancel={() => setEditing(undefined)} onSaved={async () => { await invalidate(); setEditing(undefined); }} /> : null}</Modal></section>;
}

function CurriculumSubjectsPanel({ schoolId, version, canManage, onClose }: { schoolId: string; version: CurriculumVersionDto; canManage: boolean; onClose: () => void }) {
  const queryClient = useQueryClient();
  const [page, setPage] = useState(1);
  const [editing, setEditing] = useState<CurriculumSubjectDto | null | undefined>();
  const [notice, setNotice] = useState<string>();
  const params = { page, pageSize: 20 };
  const query = useQuery({ queryKey: academicKeys.curriculumSubjects(schoolId, version.id, params), queryFn: () => academicApi.curriculumSubjects(version.id, params) });
  const allAttached = useQuery({ queryKey: academicKeys.selectors(schoolId, `curriculum-subjects-${version.id}`), queryFn: () => academicApi.allCurriculumSubjects(version.id) });
  const subjects = useQuery({ queryKey: academicKeys.selectors(schoolId, 'subjects'), queryFn: academicApi.allSubjects });
  const attached = new Set(allAttached.data?.map((item) => item.subjectId) ?? []);
  const hasAvailableSubject = subjects.data?.some((subject: SubjectDto) => subject.status === 'ACTIVE' && !attached.has(subject.id)) ?? false;
  const invalidate = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['academic', schoolId, 'curriculum-subjects', version.id] }), queryClient.invalidateQueries({ queryKey: academicKeys.selectors(schoolId, `curriculum-subjects-${version.id}`) })]); setNotice(t.mutationSuccess); };
  const editable = canManage && version.status === 'DRAFT';
  return <section className="space-y-4 rounded-lg border bg-background p-4"><SectionHeader title={`${t.curriculumSubjects} — ${version.name}`} description={t.draftOnly} action={<div className="flex gap-2">{editable ? <Button type="button" size="sm" disabled={!hasAvailableSubject || allAttached.isPending} onClick={() => setEditing(null)}><Plus className="size-4" aria-hidden="true" />{t.attachSubject}</Button> : null}<Button type="button" size="sm" variant="outline" onClick={onClose}>{t.cancel}</Button></div>} />{notice ? <InlineFeedback kind="success">{notice}</InlineFeedback> : null}{query.isError || allAttached.isError ? <ApiErrorState title={t.listError} onRetry={() => { void query.refetch(); void allAttached.refetch(); }} /> : <><TableShell headers={[t.displayOrder, t.subject, t.coefficient, t.status, t.actions]} loading={query.isPending || subjects.isPending || allAttached.isPending}>{query.data?.data.length === 0 ? <EmptyTableRow columns={5} /> : query.data?.data.map((item) => <tr key={item.id}><td className="px-4 py-3">{item.displayOrder ?? '—'}</td><td className="px-4 py-3 font-medium">{item.subjectName}{item.subjectCode ? <span className="ms-2 text-xs text-muted-foreground">{item.subjectCode}</span> : null}</td><td className="px-4 py-3 font-mono">{item.coefficient}</td><td className="px-4 py-3"><StatusBadge status={item.status} /></td><td className="px-4 py-3"><div className="flex justify-end gap-1">{editable ? <><Button type="button" variant="ghost" size="sm" aria-label={`${t.edit} ${item.subjectName}`} onClick={() => setEditing(item)}><Pencil className="size-4" aria-hidden="true" /></Button><LifecycleActions resourceName={item.subjectName} path={`/api/v1/curriculum-subjects/${item.id}`} transitions={activeTransitions(item.status)} onSaved={invalidate} /></> : null}</div></td></tr>)}</TableShell>{query.data ? <Pagination {...query.data.meta} onPage={setPage} /> : null}</>}{editable && !hasAvailableSubject && query.data?.data.length ? <p className="text-sm text-muted-foreground">{t.duplicateSubject}</p> : null}<Modal open={editing !== undefined} title={editing ? t.editCurriculumSubject : t.attachSubject} description={t.noCoefficientOnSubject} onClose={() => setEditing(undefined)}>{editing !== undefined && subjects.data ? <CurriculumSubjectForm version={version} subjects={subjects.data} attachedSubjectIds={attached} initial={editing ?? undefined} onCancel={() => setEditing(undefined)} onSaved={async () => { await invalidate(); setEditing(undefined); }} /> : null}</Modal></section>;
}
